apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saleor-backend-hpa
  namespace: saleor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saleor-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
