apiVersion: v1
kind: Secret
metadata:
  name: saleor-db-secret
  namespace: saleor
type: Opaque
data:
  POSTGRES_PASSWORD: 
  DATABASE_URL: cG9zdGdyZXNxbDovL3NhbGVvcmFkbWluOnNhbGVvcnBhc3N3b3JkQHNhbGVvcmRhdGFiYXNlLmN4ZzBlOGcwdTF1ZC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9zYWxlb3JkYXRhYmFzZQ==
  SECRET_KEY: 
  RSA_PRIVATE_KEY: 
  RSA_PUBLIC_KEY: 

